version: '3.7'

services:
        users:
         build:
          context: ./services/users
          dockerfile: Dockerfile-stage
         ports:
          - 5001:5000
         expose:
          - 5000
         environment:
          - FLASK_ENV=production
          - APP_SETTINGS=project.config.StagingConfig
          - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_stage
          - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
          - SECRET_KEY=my_precious
         depends_on:
          - users-db
        users-db:
         build:
          context: ./services/users/project/db
          dockerfile: Dockerfile
         ports:
          - 5345:5342
         expose:
          - 5342
         environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        nginx:
         build:
          context: ./services/nginx
          dockerfile: Dockerfile-stage
         restart: always
         ports: 
          - 80:80
         depends_on:
          - users
          - client
        client:
         build:
          context: ./services/client
          dockerfile: Dockerfile-stage
         ports:
          - 3007:80
         expose:
          - 80
         environment:
          - NODE_ENV=production
          - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
         depends_on:
          - users
        swagger:
         build:
          context: ./services/swagger
          dockerfile: Dockerfile-stage
         ports:
          - 3008:3000
         expose:
          - 8080
         environment:
          - URL=swagger.json
         depends_on:
          - users
           
           
